server:
  #配置访问端口
  port: 8090

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #配置数据来源
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf-8
      username: root
      password:
  http:
    #配置文件上传
    multipart:
      #单个文件上传最大大小
      max-file-size: 100MB
      max-request-size: 300MB
      enabled: true

#配置pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis:
  #给实体对象取别名
  type-aliases-package: cn.com.huzhan.springboot.entity
  configuration:
    #配置日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启mybatis二级缓存
    cache-enabled: true
    #开启懒加载
    lazy-loading-enabled: true
    #false为按需加载
    aggressive-lazy-loading: false
  mapper-locations: classpath:mapper/*.xml
